### ISSUE TITLE
error capture

### ISSUE THREAD

**Issue by xurwxj** [sunny/craster#1]
```sh
$ craster -u http://xxx.stl -n 10 -x 3 -y 15
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn phantomjs ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
  at child_process.js:1144:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by sunny** [comment]
Hi @xurwxj! That's a weird error. Are you sure you have phantomjs installed? Can you try the following in a terminal?

```sh
phantomjs -v
```

**Comment by xurwxj** [comment]
Hi sunny! phantomjs installed not fully. i done it after reinstall phantomjs.
thanks.

**Comment by sunny** [comment]
Awesome! I'll add to the README to install PhantomJS as well.

Thanks for submitting the issue.
